VERSION="2.4.1"
NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

ACCOUNTS=[
	"GD7G6ZAUGH2CGO3LIJO5JDVGSNAHKDIQO6GXDNEWD2N2JI7EUKI4ZYJL",
  	"GCOFMGR57KHY7AVLFX7NARP25ZIMOLYJRNLNMNBXZ3BFL2VF5M3IBHHF",
]

[DOCUMENTATION]
ORG_NAME="Manangos"
ORG_URL="https://manangos2.tk/"
ORG_LOGO="https://manangos2.tk/img/manangos.png"
ORG_DESCRIPTION="The revival of the fork of the fork of another fork"
ORG_TWITTER="@Manangos2"
ORG_OFFICIAL_EMAIL="stellarmangos2@gmail.com"

[[PRINCIPALS]]
name="Smoothie"
email="stellarmangos2@gmail.com"

[[CURRENCIES]]
code="Manangos"
issuer="GD7G6ZAUGH2CGO3LIJO5JDVGSNAHKDIQO6GXDNEWD2N2JI7EUKI4ZYJL"
name="Manangos"
desc="Manangos: Better Than Ever!"
image="https://manangos2.tk/img/manangos.png"
display_decimals=6
conditions="There will be only 52 billion Manangos in existence."
fixed_number=52000069420
