# stellar.toml file for Mango

NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"

ACCOUNTS = [
  "GASGDM5JZ6UZETZ6POVYYJWIF2GCIGYKSUQP3CIMUWFE4HB5SEUQSLUT", # Mango Issuer
  "GAQFGRP2MDDGD6JI5GSHLAYJYWZ5OKWM3GQDF6ID4JZBIZZL2GBKCOIN" # Mango Distro
]

[DOCUMENTATION]
ORG_NAME = "Mango"
ORG_URL = "https://www.mangocoin.space"
ORG_DESCRIPTION = "Mango to the trees!!."
ORG_LOGO = "https://pplx-res.cloudinary.com/image/upload/v1744172970/user_uploads/sZPiuDrAfmtZJli/Mango-256x256.jpg"
ORG_TWITTER="@MangoCrypto2"
ORG_OFFICIAL_EMAIL="stellarmangos2@gmail.com"

[[PRINCIPALS]]
name="Smoothie"
email="stellarmangos2@gmail.com"

[[CURRENCIES]]
code = "Mango"
issuer = "GASGDM5JZ6UZETZ6POVYYJWIF2GCIGYKSUQP3CIMUWFE4HB5SEUQSLUT"
name = "Mango"
desc = "Mango: Better Than Ever!"
image = "https://pplx-res.cloudinary.com/image/upload/v1744172970/user_uploads/sZPiuDrAfmtZJli/Mango-256x256.jpg"
display_decimals = 6
status = "live"
conditions = "Total Market Cap 52 Billion Mangos 🥭"
fixed_number = 5242042069
is_asset_anchored = false  # Required field[^2]
